# NVIDIA-DEVICE-PLUGIN CONFIGURATION
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  hostIPC: true
  restartPolicy: Never
  # securityContext:
  #   runAsUser: 1000   # NO NEED
  containers:
  - name: cnn-container
    image: synergcseiitb/bart-large-cnn-text_summarization
    imagePullPolicy: Never
    ports:
    - containerPort: 4444
    resources:
      limits:
        nvidia.com/gpu: 1 # 1 PHYSICAL GPU